<?php

return [
    'backend_disable_self_ping'           => 0,
    'backend_disable_self_ping_urls'      => '',
    'backend_disable_rss_feed'            => 0,
    'backend_disable_xmlrpc'              => 0,
    'revisions_disable_revisions'         => [ 'no' ],
    'editor_disable_autosave'             => 'no',
    'editor_autosave_interval'            => '',
    'editor_disable_classic_theme_styles' => 0,
    'editor_disable_texturization'        => 0,
    'editor_disable_capital_p'            => 0,
    'editor_disable_autop'                => 0,
    'privacy_hide_wp_version'             => 0,
    'privacy_fake_user_agent_value'       => 0,
    'tracking_allow_usage_tracking'       => 0,
    'xmlrpc_disable_xmlrpc'               => 'no',
    'updates_disable_updates'             => 'no',
    'performance_disable_emojis'          => 0,
    'performance_disable_embeds'          => 0,
    'performance_disable_heartbeat'       => 'no',
    'performance_heartbeat_frequency'     => '',
    'performance_disable_widgets'         => 'no',
];
