/**
 * Webpack configuration file.
 */

// WordPress webpack config.
const [ scriptConfig ] = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin        = require( 'webpack-remove-empty-scripts' );
const RtlCssPlugin    = require( '@wordpress/scripts/plugins/rtlcss-webpack-plugin' );

// Utilities.
const path         = require( 'node:path' );

/**
 * Exports the custom webpack config.
 */
module.exports = ( () => {
  return [
    {
      // Includes the default webpack config from WordPress.
      ...scriptConfig,
      ...{
        entry: {
          'js/admin/tabs'                  : path.resolve( process.cwd(), 'resources/js', 'admin/tabs.js' ),
          'js/admin/settings'              : path.resolve( process.cwd(), 'resources/js', 'admin/settings.js' ),
          'js/blocks/disable-embeds/index' : path.resolve( process.cwd(), 'resources/js', 'blocks/disable-embeds/index.js' ),

          'css/admin/notices'  : path.resolve( process.cwd(), 'resources/scss', 'admin/notices.scss' ),
          'css/admin/settings' : path.resolve( process.cwd(), 'resources/scss', 'admin/settings.scss' ),
        },
        plugins: [
          // Very important! Include WP's plugin config or the
          // world will cease to exist as we know it. This also
          // removes the RTL handling for the moment, but it
          // should be re-added at a later date.
          ...scriptConfig.plugins.filter(
            filter => !( filter instanceof RtlCssPlugin ),
          ),

          // Removes the empty `.js` files generated by webpack.
          // For this to work correctly, it needs to run after
          // WP has generated the `*.asset.php` files. This is
          // what `STAGE_AFTER_PROCESS_PLUGINS` allows.
          new RemoveEmptyScriptsPlugin( {
            stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
          } ),
        ],
      },
    },
  ];
} )();
