<?php

return [
    'rss_feed_redirect'              => [
        'id'          => 'rss_feed_redirect',
        'title'       => esc_html__( 'Redirect feeds (if disabled)', 'hbp-disabler' ),
        'type'        => 'select',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'setting_key' => 'feeds_rss_feed_redirect',
        'choices'     => [
            'redirect' => 'Redirect to homepage',
            '404'      => '404',
        ],
    ],
    'disable_feed_global'            => [
        'id'          => 'disable_feed_global',
        'title'       => esc_html__( 'Disable global feed', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing an overview of recent posts. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Feed" href="https://www.example.com/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_global',
    ],
    'disable_feed_global_comments'   => [
        'id'          => 'disable_feed_global_comments',
        'title'       => esc_html__( 'Disable global comment feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( ' Removes URLs providing an overview of recent comments. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Comments Feed" href="https://www.example.com/comments/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_global_comments',
        'description' => esc_html__( 'Also disables post comment feeds.', 'hbp-disabler' ),
    ],
    'disable_feed_post_comments'     => [
        'id'          => 'disable_feed_post_comments',
        'title'       => esc_html__( 'Disable post comments feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing recent comments on each post. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Example post Comments Feed" href="https://www.example.com/example-post/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_post_comments',
    ],
    'disable_feed_authors'           => [
        'id'          => 'disable_feed_authors',
        'title'       => esc_html__( 'Disable post authors feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing recent posts by specific authors. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Posts by Example Author Feed" href="https://www.example.com/author/example-author/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_authors',
    ],
    'disable_feed_post_types'        => [
        'id'          => 'disable_feed_post_types',
        'title'       => esc_html__( 'Disable post type feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing recent posts for each post type. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Movies Feed" href="https://www.example.com/movies/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_post_types',
    ],
    'disable_feed_categories'        => [
        'id'          => 'disable_feed_categories',
        'title'       => esc_html__( 'Disable category feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing recent posts for each category. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - News Category Feed" href="https://www.example.com/category/news/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_categories',
    ],
    'disable_feed_tags'              => [
        'id'          => 'disable_feed_tags',
        'title'       => esc_html__( 'Disable tag feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing recent posts for each tag. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Blue Tag Feed" href="https://www.example.com/tag/blue/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_tags',
    ],
    'disable_feed_custom_taxonomies' => [
        'id'          => 'disable_feed_custom_taxonomies',
        'title'       => esc_html__( 'Disable custom taxonomy feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing recent posts for each custom taxonomy. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Large size Feed" href="https://www.example.com/size/large/feed/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_custom_taxonomies',
    ],
    'disable_feed_search'            => [
        'id'          => 'disable_feed_search',
        'title'       => esc_html__( 'Disable search results feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs providing search result information. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Search Results for \'example\' Feed" href="https://www.example.com/search/example/feed/rss2/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_feed_search',
    ],
    'disable_atom_rdf_feeds'         => [
        'id'          => 'disable_atom_rdf_feeds',
        'title'       => esc_html__( 'Disable Atom / RDF feeds', 'hbp-disabler' ),
        'type'        => 'checkbox',
        'page'        => 'settings_page_hbp-disabler-settings',
        'section'     => 'feeds',
        'after_field' => sprintf( 'Removes URLs that provide alternative (legacy) formats of the above. E.g., %1$s', '<br/><code>' . esc_html( '<link rel="alternate" type="application/rss+xml" title="Example Website - Feed" href="https://www.example.com/feed/atom/" />' ) . '</code>' ),
        'setting_key' => 'feeds_disable_atom_rdf_feeds',
    ],
];
